language: julia
os:
  - linux
julia:
  # - 0.7
  - nightly
notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - julia -e 'Pkg.add("Documenter"); Pkg.add("Literate")'
  - julia -e 'cd(Pkg.dir("JuliaMusic_documentation")); include(joinpath("docs", "make.jl"))'
