language: julia
os:
  - linux
julia:
  # - 0.7
  - nightly
notifications:
  email:
    on_success: never
    on_failure: never

before_install: sudo pip istall --upgrade pip

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Literate")'
  - julia -e 'using Pkg; Pkg.add("MIDI"); Pkg.add("MotifSequenceGenerator"); Pkg.add("MusicManipulations")'
  - julia -e 'using Pkg, JuliaMusic_documentation; cd(joinpath(dirname(pathof(JuliaMusic_documentation)), "..")); include(joinpath("docs", "make.jl"))'
