language: julia
os:
  - linux

julia:
  - 1

notifications:
  email:
    on_success: never
    on_failure: never

# before_install:
#   - apt-get install -y musescore

before_script:
  - julia -e 'using Pkg; ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.build(); Pkg.add("PyPlot")'

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Literate"); Pkg.add("DocumenterMarkdown")'
        - julia -e 'using Pkg; Pkg.add("MIDI"); Pkg.add("MotifSequenceGenerator"); Pkg.add("MusicManipulations");'
        - julia -e 'using Pkg, JuliaMusic_documentation; cd(joinpath(dirname(pathof(JuliaMusic_documentation)), "..")); include(joinpath("docs", "make.jl"))'
