language: julia
os:
  - linux
julia:
  # - 0.7
  - nightly
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/JuliaMusic/MusicManipulations.jl"); Pkg.clone(pwd())'
after_success:
  - julia -e julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("JuliaMusic_documentation")); include(joinpath("docs", "make.jl"))'
