language: julia
os:
  - linux

julia:
  - 1.1

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email:
    on_success: never
    on_failure: never

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Literate"); Pkg.add("DocumenterMarkdown")'
        - julia -e 'using Pkg; Pkg.add("MIDI"); Pkg.add("MotifSequenceGenerator"); Pkg.add("MusicManipulations"); Pkg.add("https://github.com/JuliaMusic/JuliaMusic_documentation.jl")'
        - julia -e 'using Pkg, JuliaMusic_documentation; cd(joinpath(dirname(pathof(JuliaMusic_documentation)), "..")); include(joinpath("docs", "make.jl"))'
