site_name:           JuliaMusic
repo_url:            https://github.com/JuliaMusic
site_description:    Julia packages for handling and manipulating music-related data.
site_author:         George Datseris, Joel Hobson

theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'pink'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/JuliaMusic'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.details
  - mdx_math
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets\Documenter.css


extra_javascript:
  - assets\mathjaxhelper.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

docs_dir: 'build'

pages:
- Introduction: index.md
- MIDI files: midi/io.md
- Notes: midi/notes.md
- Quantizing: mm/quantizing.md
- Music Data Extraction: mm/extraction.md
